---
- hosts: localhost
  vars:
    mytext: |
      hello,
      there how   are
      you,?
  tasks:
    - debug:
        msg: "{{ mytext }}"
    - debug:
        msg: "{{ mytext.split(',')[2] }}"
    - debug:
        msg: "{{ mytext.split() | join(' ') }}"
